version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net
    # restart: always

  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   container_name: redisinsight
  #   ports:
  #     - "8001:8001"
  #   networks:
  #     - redis-net
  #   restart: always

volumes:
  redis-data:

networks:
  redis-net:
    driver: bridge
